
export default function TermsOfService() {
  return (
    <main style={{ maxWidth: 800, margin: "0 auto", padding: "60px 24px", fontFamily: "sans-serif", lineHeight: 1.7, color: "#222" }}>
      <h1>Terms of Service</h1>
      <p><em>Last updated: 31 May 2026</em></p>

      <p>These Terms of Service govern your use of Swift AI Marketing, operated by Swift AI Marketing, Switzerland ("<strong>we</strong>", "<strong>us</strong>"). By creating an account you agree to these terms.</p>

      <h2>1. The service</h2>
      <p>Swift AI Marketing provides AI-powered tools for small and medium businesses to generate social media content, landing pages, and marketing materials, and to publish content to connected social media accounts.</p>

      <h2>2. Your account</h2>
      <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your password. You must be at least 18 years old and authorised to act on behalf of any business you register.</p>

      <h2>3. Acceptable use</h2>
      <p>You may not use the service to:</p>
      <ul>
        <li>Generate or publish content that is illegal, defamatory, or infringes third-party intellectual property.</li>
        <li>Violate Meta Platform Terms, Instagram Community Guidelines, or any applicable social platform policy.</li>
        <li>Attempt to reverse-engineer, scrape, or overload the service.</li>
        <li>Resell or sublicense the service without written permission.</li>
      </ul>

      <h2>4. AI-generated content</h2>
      <p>Content generated by our AI tools is provided as a starting point. You are responsible for reviewing content before publishing and for ensuring it complies with applicable laws and platform policies. We do not guarantee that AI-generated content is accurate, complete, or suitable for your purposes.</p>

      <h2>5. Social media integrations</h2>
      <p>When you connect a Facebook Page or Instagram account, you authorise us to publish content on your behalf. You remain solely responsible for all content published through your connected accounts. You may disconnect your accounts at any time from the Integrations page.</p>

      <h2>6. Billing</h2>
      <p>Subscriptions are billed monthly or annually in advance via Stripe. You may cancel at any time; cancellation takes effect at the end of the current billing period. We do not offer refunds for partial periods. We reserve the right to modify pricing with 30 days notice.</p>

      <h2>7. Intellectual property</h2>
      <p>You retain ownership of all content you create using the service. You grant us a limited licence to process and store your content solely to operate the service. We retain ownership of the platform, software, and AI models.</p>

      <h2>8. Limitation of liability</h2>
      <p>To the maximum extent permitted by Swiss law, we are not liable for indirect, incidental, or consequential damages arising from your use of the service, including but not limited to loss of revenue, loss of data, or social media account suspension. Our total liability is limited to the fees you paid in the 3 months preceding the claim.</p>

      <h2>9. Termination</h2>
      <p>We may suspend or terminate your account if you breach these terms, with or without notice depending on severity. You may delete your account at any time from the account settings page.</p>

      <h2>10. Governing law</h2>
      <p>These terms are governed by Swiss law. Any disputes shall be subject to the exclusive jurisdiction of the courts of Switzerland.</p>

      <h2>11. Changes</h2>
      <p>We may update these terms. We will notify you by email at least 14 days before material changes take effect.</p>

      <h2>12. Contact</h2>
      <p><a href="mailto:abdi@swiftapp.ch">abdi@swiftapp.ch</a></p>
    </main>
  );
}
